name: lint-unittest

on:
  push:
    branches:
      - "feature*"

jobs:
  lint-and-unittest:
    name: Run tests and coverage
    runs-on: ubuntu-latest
    steps:
      # See: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
      # See: https://github.com/actions/setup-python
      - name: Set up Python "3.13"
        uses: actions/setup-python@v1
        with:
          python-version: "3.13"
      # install poetry and deps
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.create false
          poetry install --no-root
          echo "# Installed packages shown below"
          poetry show --tree
      # lint
      - name: Run Ruff (lint)
        run: poetry run ruff check --output-format=github .
      # test
      - name: Run Tests
        run: |
          set -o pipefail
          poetry run pytest --junitxml=pytest.xml --cov-report=term-missing --cov=src tests/ | tee pytest-coverage.txt
      # post coverage report
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
